---
- hosts: all
  become: true
  roles:
    - role: pkorobeinikov.locale
      locale_names:
        - en_US.UTF-8
      locale_env_vars:
        - LC_ALL=en_US.UTF-8
        - LANG=en_US.UTF-8

    - role: pkorobeinikov.tzdata
      tzdata_timezone: Europe/Moscow
